### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by binarydad** [nioc/xmpp-web#47]
Wondering if so, or if there are active forks. This is certainty the most polished XMPP UI I've seen, though it has some quirks I'm noticing.

**Comment by nioc** [comment]
Hello @binarydad yes it is. There is two active items on development:

- #45 Technical update to Vue 3 (I have an issue bundling stanza dependency), this is the highest priority,
- #38 "Light theme" feature request, for which I am waiting CSS part...

If you have any feedback / suggestion, please do not hesitate to come forward 😄

**Comment by binarydad** [comment]
Awesome! I'm really digging this app, and have been looking for a good XMPP web client for a while (and I really don't like converse.js). 

Some suggestions (LMK if you're prefer a separate issue). Keep in mind I'm not an XMPP expert, so apologies if I use the wrong terminology:

1. Show the contact's actual name instead of email identifier. Currently, my contacts on the left show up as **name@xmppserver.com** instead of just **Name**
2. Every time I click on a contact, it loads an empty conversation. I have to click the "Get history" icon every time. It keeps the history loaded when I toggle between contacts/conversations, but when I refresh, it goes away.

Those are the only two I would consider show-stoppers. BTW I'm running via docker and have not yet applied any reverse proxy rewrites, so I'm hitting the docker port directly. 

Some over nice-to-haves:

1. Read and received indicators (checkmarks, double checkmarks, etc)
2. A GIF picker would be amazing if feasible

All I can think of for now.

**Comment by nioc** [comment]
1. I have to check what is sent by XMPP server, if nickname is sent, it should be possible to add a setting to use it instead of full Jid (JabberIdentifier). I think it is better to have the full, as you can have several contact with same name on different servers.
2. to be checked but seems possible to process an automatic `searchHistory` when opening for the first time a conversation with a contact.
As you proposed, you can create one issue for each of these item.

For nice to haves (which are really optional 😆 ):

1. it is #4 but I did not found time for it...
2. If you knows a small footprint VueJS component that doing it, let me know.

For the moment, I have to finish the bundling part to package stanza with rollup, which is such a pain...
