### ISSUE TITLE
Update login username placeholder to only request "user" instead of "email"

### ISSUE THREAD

**Issue by binarydad** [nioc/xmpp-web#56]
As mentioned in https://github.com/nioc/xmpp-web/issues/53, the full user@domain is no longer required, so it seems fitting that the field placeholder also matches. 

![image](https://user-images.githubusercontent.com/1760607/171066295-1b46170e-615f-44db-a743-f7aa1de8d532.png)

**Comment by nioc** [comment]
As mentioned in my [last comment](https://github.com/nioc/xmpp-web/issues/53#issuecomment-1141003864), user can either login with just local jid (using default domain) or full jid.
Some users [requested a feature](https://github.com/nioc/xmpp-web/issues/7#issuecomment-573342520) for setting custom websocket transport url.
I think it is easier to understand if placeholder mention xmpp domain.

What I can do is to set the domain in placeholder with the default domain instead of hard-coded one.
