### ISSUE TITLE
Display room information within the room

### ISSUE THREAD

**Issue by Ppjet6** [nioc/xmpp-web#79]
**Is your feature request related to a problem? Please describe.**
After joining a room I have no way to know where I am without going back and making sure I've clicked the correct room.

Somewhat related to #78.

**Describe the solution you'd like**
I wonder if it would be useful to display either the room name or the room avatar, or both. As you may have noticed in other issues I'm not especially good with UI.

This is while using the guest mode. I don't know if it changes anything.

**Comment by nioc** [comment]
Hello, as you can see on the [screenshot](https://github.com/nioc/xmpp-web/blob/master/docs/screenshot-mobile-chat.png), in registered mode, you have a header displaying room jid.
I removed it in guest mode because there is no status switch or contact list to handle.
May be adding a specific header with relevant room information is a good idea?

**Comment by nioc** [comment]
Handling it by adding the room jid as title in the `message` component used for #78.
